name: This is a new Workflow
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm i
      - name: Testing started
        run: npm run build
      