name: This is a new Workflow
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: npm i
      - name: Testing started
        run: npm run lint
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: npm i
      - name: Testing started
        run: npm run build
      