name: This is a new Workflow
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Node
        run: npm i
      - name: Testing started
        run: npm run build
      